/** @type {import("@docusaurus/plugin-content-docs").SidebarsConfig} */
module.exports = {
  docsSidebar: [
    {
      type: "doc",
      id: "quickstart",
      label: "Home",
    },
    {
      type: "category",
      label: "Getting Started",
      items: [
        {
          type: "doc",
          id: "getting-started/index",
          label: "Overview",
        },
        {
          type: "doc",
          id: "quick-start",
          label: "Quick Start",
        },
        {
          type: "doc",
          id: "getting-started/changelog",
          label: "Changelog",
        },
      ],
    },
    {
      type: "category",
      label: "Core Concepts",
      items: [
        {
          type: "doc",
          id: "core-concepts/index",
          label: "Overview",
        },
        {
          type: "doc",
          id: "ARCHITECTURE",
          label: "Architecture",
        },
        {
          type: "doc",
          id: "design-docs/execution-modes",
          label: "Execution Modes",
        },
        {
          type: "doc",
          id: "adr/README",
          label: "Architecture Decisions",
        },
        {
          type: "link",
          label: "Specialists",
          href: "/specialists",
        },
      ],
    },
    {
      type: "category",
      label: "Platforms",
      items: [
        {
          type: "doc",
          id: "platforms/index",
          label: "Overview",
        },
        {
          type: "doc",
          id: "platforms/desktop",
          label: "Desktop",
        },
        {
          type: "doc",
          id: "platforms/cli",
          label: "CLI",
        },
        {
          type: "doc",
          id: "platforms/web",
          label: "Web",
        },
      ],
    },
    {
      type: "category",
      label: "Deployment",
      items: [
        {
          type: "doc",
          id: "deployment/index",
          label: "Deployment Overview",
        },
        {
          type: "doc",
          id: "release-guide",
          label: "Release Guide",
        },
      ],
    },
    {
      type: "category",
      label: "Configuration",
      items: [
        {
          type: "doc",
          id: "configuration/index",
          label: "Overview",
        },
        {
          type: "doc",
          id: "configuration/providers-and-models",
          label: "Providers and Models",
        },
        {
          type: "doc",
          id: "configuration/environment-variables",
          label: "Environment Variables",
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      items: [
        {
          type: "doc",
          id: "reference/index",
          label: "Overview",
        },
        {
          type: "doc",
          id: "product-specs/FEATURE_TREE",
          label: "Product Specs",
        },
        {
          type: "link",
          label: "Specialists",
          href: "/specialists",
        },
        {
          type: "doc",
          id: "release-guide",
          label: "Release Guide",
        },
        {
          type: "doc",
          id: "coding-style",
          label: "Code Style",
        },
      ],
    },
    {
      type: "category",
      label: "Deep Dives",
      items: [
        {
          type: "autogenerated",
          dirName: "design-docs",
        },
        {
          type: "autogenerated",
          dirName: "exec-plans",
        },
      ],
    },
    {
      type: "category",
      label: "Product Specs",
      items: [
        {
          type: "autogenerated",
          dirName: "product-specs",
        },
      ],
    },
    {
      type: "category",
      label: "Additional Docs",
      items: [
        {
          type: "autogenerated",
          dirName: "references",
        },
        {
          type: "autogenerated",
          dirName: "releases",
        },
        {
          type: "autogenerated",
          dirName: "features",
        },
        {
          type: "autogenerated",
          dirName: "specialists",
        },
      ],
    },
  ],
};
